name: Deploy Site Styles

on:
    workflow_dispatch:
        inputs:
            environment:
                type: environment
                description: Select the sandbox environment

jobs:
    build:
        name: Build Styles
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  ref: main
            - uses: actions/setup-node@v4
              with:
                  node-version: 20.x
            - run: npm install -g yarn
            - name: Setup Yarn in Node
              uses: actions/setup-node@v4
              with:
                  cache: 'yarn' # uses the system node, which was updated prior.
            - run: yarn install --frozen-lockfile
            - name: Build Styles
              run: yarn run dev:postcss:production

    deploy:
        name: Deploy Styles
        needs: build
        runs-on: ubuntu-latest

